<template>
  <div id="app">
    <PageHeader/>

    <transition name="fade" mode="out-in">
      <router-view/>
    </transition>

    <PageFooter/>
  </div>
</template>

<style>
body {
  margin: 0;
  padding: 0;
  font-family: "Helvetica";
}

#app {
  margin: auto;
  max-width: 1200px;
}

a {
  color: #000;
  text-decoration: none;
}

/* ROUTE TRANSITION */

.fade-enter-active,
.fade-leave-active {
  transition-duration: 0.3s;
  transition-property: opacity;
  transition-timing-function: ease;
}

.fade-enter,
.fade-leave-active {
  opacity: 0;
}

/*FONTS*/

/*Helvetica*/

@font-face {
  font-family: "Helvetica";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica"), url("assets/fonts/Helvetica.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Oblique"),
    url("assets/fonts/Helvetica-Oblique.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Compressed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Compressed"),
    url("assets/fonts/helvetica-compressed-5871d14b6903a.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Rounded Bold";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Rounded Bold"),
    url("assets/fonts/helvetica-rounded-bold-5871d05ead8de.woff") format("woff");
}

@font-face {
  font-family: "Helvetica";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica"),
    url("assets/fonts/Helvetica-Bold.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Bold Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Bold Oblique"),
    url("assets/fonts/Helvetica-BoldOblique.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Light";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Light"),
    url("assets/fonts/helvetica-light-587ebe5a59211.woff") format("woff");
}

/*Helvetica Neue*/

/* #### Generated By: http://www.cufonfonts.com #### */

@font-face {
  font-family: "Helvetica Neue Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Italic"),
    url("assets/fonts/HelveticaNeueItalic.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 35 Thin";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 35 Thin"),
    url("assets/fonts/HelveticaNeue-Thin.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 37 Thin Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 37 Thin Condensed"),
    url("assets/fonts/HelveticaNeue-ThinCond.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 37 Thin Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 37 Thin Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-ThinCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 33 Thin Extended Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 33 Thin Extended Oblique"),
    url("assets/fonts/HelveticaNeue-ThinExtObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 36 Thin Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 36 Thin Italic"),
    url("assets/fonts/HelveticaNeue-ThinItalic.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 43 Light Extended";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 43 Light Extended"),
    url("assets/fonts/HelveticaNeue-LightExt.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 27 Ultra Light Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 27 Ultra Light Condensed"),
    url("assets/fonts/HelveticaNeue-UltraLigCond.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 23 Ultra Light Extended";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 23 Ultra Light Extended"),
    url("assets/fonts/HelveticaNeue-UltraLigExt.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 47 Light Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 47 Light Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-LightCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 43 Light Extended Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 43 Light Extended Oblique"),
    url("assets/fonts/HelveticaNeue-LightExtObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 27 Ultra Light Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 27 Ultra Light Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-UltraLigCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 83 Heavy Extended";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 83 Heavy Extended"),
    url("assets/fonts/HelveticaNeue-HeavyExt.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 53 Extended";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 53 Extended"),
    url("assets/fonts/HelveticaNeue-Extended.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 85 Heavy";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 85 Heavy"),
    url("assets/fonts/HelveticaNeue-Heavy.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 87 Heavy Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 87 Heavy Condensed"),
    url("assets/fonts/HelveticaNeue-HeavyCond.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 107 Extra Black Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 107 Extra Black Condensed"),
    url("assets/fonts/HelveticaNeue-ExtBlackCond.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 57 Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 57 Condensed"),
    url("assets/fonts/HelveticaNeue-Condensed.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 63 Medium Extended";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 63 Medium Extended"),
    url("assets/fonts/HelveticaNeue-MediumExt.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 55 Roman";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 55 Roman"),
    url("assets/fonts/HelveticaNeue-Roman.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 83 Heavy Extended Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 83 Heavy Extended Oblique"),
    url("assets/fonts/HelveticaNeue-HeavyExtObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 87 Heavy Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 87 Heavy Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-HeavyCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 53 Extended Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 53 Extended Oblique"),
    url("assets/fonts/HelveticaNeue-ExtendedObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 107 Extra Black Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 107 Extra Black Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-ExtBlackCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 57 Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 57 Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-CondensedObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 86 Heavy Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 86 Heavy Italic"),
    url("assets/fonts/HelveticaNeue-HeavyItalic.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 63 Medium Extended Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 63 Medium Extended Oblique"),
    url("assets/fonts/HelveticaNeue-MediumExtObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 73 Bold Extended";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 73 Bold Extended"),
    url("assets/fonts/HelveticaNeue-BoldExt.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 73 Bold Extended Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 73 Bold Extended Oblique"),
    url("assets/fonts/HelveticaNeue-BoldExtObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 77 Bold Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 77 Bold Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-BoldCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 93 Black Extended";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 93 Black Extended"),
    url("assets/fonts/HelveticaNeue-BlackExt.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 95 Black";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 95 Black"),
    url("assets/fonts/HelveticaNeue-Black.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 93 Black Extended Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 93 Black Extended Oblique"),
    url("assets/fonts/HelveticaNeue-BlackExtObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Neue UltraLight";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue UltraLight"),
    url("assets/fonts/HelveticaNeueUltraLight.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Neue UltraLight Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue UltraLight Italic"),
    url("assets/fonts/HelveticaNeueUltraLightItal.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 45 Light";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 45 Light"),
    url("assets/fonts/HelveticaNeue-Light.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Neue Light";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Light"),
    url("assets/fonts/HelveticaNeueLight.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 47 Light Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 47 Light Condensed"),
    url("assets/fonts/helvetica-47-light-condensed-587ebd7b5a6f6.woff")
      format("woff");
}

@font-face {
  font-family: "Helvetica Neue Light Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Light Italic"),
    url("assets/fonts/HelveticaNeueLightItalic.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 46 Light Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 46 Light Italic"),
    url("assets/fonts/helvetica-46-light-italic-587ebdb0ea724.woff")
      format("woff");
}

@font-face {
  font-family: "Helvetica Neue Medium";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Medium"),
    url("assets/fonts/HelveticaNeueMedium.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 67 Medium Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 67 Medium Condensed"),
    url("assets/fonts/HelveticaNeue-MediumCond.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 65 Medium";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 65 Medium"),
    url("assets/fonts/HelveticaNeue-Medium.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 67 Medium Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 67 Medium Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-MediumCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Neue Bold";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Bold"),
    url("assets/fonts/HelveticaNeueBold.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Neue Condensed Bold";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Condensed Bold"),
    url("assets/fonts/HelveticaNeueCondensedBold.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 75 Bold Outline";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 75 Bold Outline"),
    url("assets/fonts/helvetica-75-bold-outline-587ebe00b76ba.woff")
      format("woff");
}

@font-face {
  font-family: "Helvetica Neue Bold Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Bold Italic"),
    url("assets/fonts/HelveticaNeueBoldItalic.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 97 Black Condensed";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 97 Black Condensed"),
    url("assets/fonts/HelveticaNeue-BlackCond.woff") format("woff");
}

@font-face {
  font-family: "Helvetica Neue Condensed Black";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica Neue Condensed Black"),
    url("assets/fonts/HelveticaNeueCondensedBlack.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 97 Black Condensed Oblique";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 97 Black Condensed Oblique"),
    url("assets/fonts/HelveticaNeue-BlackCondObl.woff") format("woff");
}

@font-face {
  font-family: "Helvetica 96 Black Italic";
  font-style: normal;
  font-weight: normal;
  src: local("Helvetica 96 Black Italic"),
    url("assets/fonts/HelveticaBlkIt.woff") format("woff");
}
</style>

<script>
import PageHeader from '@/components/PageHeader'
import PageFooter from '@/components/PageFooter'

export default {
  name: 'app',
  components: { PageHeader, PageFooter }
}
</script>
